name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures you pull all history for version comparisons

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust your Node.js version as necessary

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Specify the path to your build directory
          path: './build'  # Update this line to point to your 'build' folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
