name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures you pull all history for version comparisons

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust your Node.js version as necessary

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy files to docs
        run: |
          rm -rf docs
          cp -r build docs

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Deploy to GitHub Pages" -a || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
